version: '3.8'

services:
  streams-app:
    build: ./target/docker/stage/
    hostname: streams-app
    env_file:
      - ./env/credentials.env

  zookeeper:
    image: "confluentinc/cp-zookeeper:6.1.0"
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    env_file:
      - ./env/zookeeper.env

  broker:
    image: "confluentinc/cp-kafka:6.1.0"
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    env_file:
      - ./env/broker.env

  schema-registry:
    image: "confluentinc/cp-schema-registry:6.1.0"
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    env_file:
      - ./env/schema-registry.env